### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by ssmith353** [metal/metal-tabs#10]
https://github.com/metal/metal-tabs/blob/d84902170c3ea4bc1107dc71088f2195e057d0e6/demos/index.html#L8

Removed here: https://github.com/metal/metal-tabs/commit/385470674bdf92e6e2a59c698fc0905b6459eab0

**Comment by jbalsas** [comment]
Removed: https://github.com/metal/metal-tabs/commit/7d3201602f899e4f67efa10cee39bba4cbdca779

Thanks!
